/**
 * Predefined mode configuration data.
 * Kept separate from the type definitions in modes.ts to prevent one large
 * file from growing with every new mode or property change.
 */
import { AMBIENT_SOUNDS } from "./modes";
import type { PlayerMode, PlayerModeConfig } from "./modes";

// ── Mood mode base ─────────────────────────────────────────────────────────
const moodBase: Omit<PlayerModeConfig, "id" | "name" | "description" | "icon" | "theme"> = {
    controls: {
        showProgressBar: true,
        showTimeDisplay: true,
        showPlaybackSpeed: false,
        showVolumeControl: true,
        showFullscreen: false,
        showChapters: false,
        showBookmarks: false,
        navigationStyle: "continuous",
        showPageControls: false,
        showPageIndicator: false,
        allowManualPageTurn: false,
        autoHideControls: true,
        autoHideDelay: 4000,
        controlsPosition: "bottom",
        controlsOpacity: 0.85,
        swipeToNavigate: false,
        tapToPlayPause: true,
        doubleTapToSeek: false,
        sleepTimer: true,
        abLoop: false,
        frameStep: false,
        annotations: false,
    },
    effects: {
        defaultFilters: {
            brightness: 1,
            contrast: 1,
            saturation: 1,
            hue: 0,
            blur: 0,
            sepia: 0,
            grayscale: 0,
        },
        transitionStyle: "fade",
        transitionDuration: 600,
        letterbox: false,
        letterboxRatio: 16 / 9,
        kenBurnsEnabled: false,
        kenBurnsIntensity: 0,
        parallaxEnabled: false,
    },
    behavior: {
        autoPlay: false,
        loop: true,
        defaultSpeed: 1,
        pauseBetweenChapters: false,
        chapterPauseDuration: 0,
        rememberPosition: false,
        showProgressOnHover: false,
        autoAdvance: true,
        advanceDelay: 0,
        requireInteraction: false,
        sleepTimerOptions: [15, 30, 60, 90],
        fadeOutOnSleep: true,
        syncTextHighlight: false,
        syncAnimations: false,
    },
    audio: {
        ambientVolume: 0,
        backgroundMusicDuck: false,
        duckAmount: 0,
        duckFadeDuration: 0,
        voiceBoost: false,
        voiceBoostAmount: 0,
        spatialAudio: false,
        transitionSoundVolume: 0,
    },
};

// ── Mode groups ────────────────────────────────────────────────────────────
export const MODE_GROUPS: { label: string; modes: PlayerMode[] }[] = [
    {
        label: "Player",
        modes: [
            "standard",
            "reader",
            "editor",
            "storyteller",
            "audiobook",
            "cinema",
            "presentation",
            "learning",
        ],
    },
    {
        label: "Experience",
        modes: ["journey", "dock", "storm", "fest", "rock", "pop", "disco", "mixer"],
    },
];

// Predefined mode configurations
export const MODE_CONFIGS: Record<PlayerMode, PlayerModeConfig> = {
    standard: {
        id: "standard",
        name: "Standard",
        description: "Default video player experience",
        icon: "play-circle",
        theme: {
            background: "#0a0a0f",
            surface: "#12121a",
            accent: "#6366f1",
            text: "#e2e8f0",
            textMuted: "#94a3b8",
            borderRadius: "md",
            shadows: "medium",
            vignette: 0,
            grain: 0,
            warmth: 0,
            saturation: 1,
        },
        controls: {
            showProgressBar: true,
            showTimeDisplay: true,
            showPlaybackSpeed: true,
            showVolumeControl: true,
            showFullscreen: true,
            showChapters: true,
            showBookmarks: true,
            navigationStyle: "continuous",
            showPageControls: false,
            showPageIndicator: false,
            allowManualPageTurn: false,
            autoHideControls: true,
            autoHideDelay: 3000,
            controlsPosition: "bottom",
            controlsOpacity: 1,
            swipeToNavigate: false,
            tapToPlayPause: true,
            doubleTapToSeek: true,
            sleepTimer: false,
            abLoop: false,
            frameStep: false,
            annotations: false,
        },
        effects: {
            defaultFilters: {
                brightness: 1,
                contrast: 1,
                saturation: 1,
                hue: 0,
                blur: 0,
                sepia: 0,
                grayscale: 0,
            },
            transitionStyle: "cut",
            transitionDuration: 0,
            letterbox: false,
            letterboxRatio: 16 / 9,
            kenBurnsEnabled: false,
            kenBurnsIntensity: 0,
            parallaxEnabled: false,
        },
        behavior: {
            autoPlay: false,
            loop: false,
            defaultSpeed: 1,
            pauseBetweenChapters: false,
            chapterPauseDuration: 0,
            rememberPosition: true,
            showProgressOnHover: true,
            autoAdvance: true,
            advanceDelay: 0,
            requireInteraction: false,
            sleepTimerOptions: [15, 30, 45, 60, 90],
            fadeOutOnSleep: true,
            syncTextHighlight: false,
            syncAnimations: false,
        },
        audio: {
            ambientVolume: 0,
            backgroundMusicDuck: false,
            duckAmount: 0.3,
            duckFadeDuration: 500,
            voiceBoost: false,
            voiceBoostAmount: 3,
            spatialAudio: false,
            transitionSoundVolume: 0,
        },
    },

    reader: {
        id: "reader",
        name: "Reader",
        description: "Document reading surface for manifests, text, Markdown, and extracted sources",
        icon: "book-open-text",
        theme: {
            background: "#f5f1e8",
            surface: "#fffdf8",
            accent: "#0f766e",
            text: "#1f2937",
            textMuted: "#6b7280",
            borderRadius: "sm",
            shadows: "soft",
            vignette: 0,
            grain: 0.02,
            warmth: 0.1,
            saturation: 1,
        },
        controls: {
            showProgressBar: false,
            showTimeDisplay: false,
            showPlaybackSpeed: false,
            showVolumeControl: false,
            showFullscreen: false,
            showChapters: true,
            showBookmarks: true,
            navigationStyle: "page-based",
            showPageControls: false,
            showPageIndicator: true,
            allowManualPageTurn: true,
            autoHideControls: false,
            autoHideDelay: 0,
            controlsPosition: "side",
            controlsOpacity: 1,
            swipeToNavigate: true,
            tapToPlayPause: false,
            doubleTapToSeek: false,
            sleepTimer: false,
            abLoop: false,
            frameStep: false,
            annotations: true,
        },
        effects: {
            defaultFilters: {
                brightness: 1,
                contrast: 1,
                saturation: 1,
                hue: 0,
                blur: 0,
                sepia: 0,
                grayscale: 0,
            },
            transitionStyle: "cut",
            transitionDuration: 0,
            letterbox: false,
            letterboxRatio: 16 / 9,
            kenBurnsEnabled: false,
            kenBurnsIntensity: 0,
            parallaxEnabled: false,
        },
        behavior: {
            autoPlay: false,
            loop: false,
            defaultSpeed: 1,
            pauseBetweenChapters: false,
            chapterPauseDuration: 0,
            rememberPosition: true,
            showProgressOnHover: false,
            autoAdvance: false,
            advanceDelay: 0,
            requireInteraction: false,
            sleepTimerOptions: [],
            fadeOutOnSleep: false,
            syncTextHighlight: true,
            syncAnimations: false,
        },
        audio: {
            ambientVolume: 0,
            backgroundMusicDuck: false,
            duckAmount: 0,
            duckFadeDuration: 0,
            voiceBoost: false,
            voiceBoostAmount: 0,
            spatialAudio: false,
            transitionSoundVolume: 0,
        },
    },

    editor: {
        id: "editor",
        name: "Editor",
        description: "Desktop-first scene and project authoring shell",
        icon: "pencil-ruler",
        theme: {
            background: "#06131a",
            surface: "#0f172a",
            accent: "#14b8a6",
            text: "#e2e8f0",
            textMuted: "#94a3b8",
            borderRadius: "md",
            shadows: "dramatic",
            vignette: 0,
            grain: 0.02,
            warmth: -0.05,
            saturation: 1,
        },
        controls: {
            showProgressBar: false,
            showTimeDisplay: false,
            showPlaybackSpeed: false,
            showVolumeControl: false,
            showFullscreen: false,
            showChapters: true,
            showBookmarks: true,
            navigationStyle: "page-based",
            showPageControls: false,
            showPageIndicator: false,
            allowManualPageTurn: true,
            autoHideControls: false,
            autoHideDelay: 0,
            controlsPosition: "side",
            controlsOpacity: 1,
            swipeToNavigate: false,
            tapToPlayPause: false,
            doubleTapToSeek: false,
            sleepTimer: false,
            abLoop: false,
            frameStep: false,
            annotations: true,
        },
        effects: {
            defaultFilters: {
                brightness: 1,
                contrast: 1,
                saturation: 1,
                hue: 0,
                blur: 0,
                sepia: 0,
                grayscale: 0,
            },
            transitionStyle: "cut",
            transitionDuration: 0,
            letterbox: false,
            letterboxRatio: 16 / 9,
            kenBurnsEnabled: false,
            kenBurnsIntensity: 0,
            parallaxEnabled: false,
        },
        behavior: {
            autoPlay: false,
            loop: false,
            defaultSpeed: 1,
            pauseBetweenChapters: false,
            chapterPauseDuration: 0,
            rememberPosition: true,
            showProgressOnHover: false,
            autoAdvance: false,
            advanceDelay: 0,
            requireInteraction: false,
            sleepTimerOptions: [],
            fadeOutOnSleep: false,
            syncTextHighlight: false,
            syncAnimations: false,
        },
        audio: {
            ambientVolume: 0,
            backgroundMusicDuck: false,
            duckAmount: 0,
            duckFadeDuration: 0,
            voiceBoost: false,
            voiceBoostAmount: 0,
            spatialAudio: false,
            transitionSoundVolume: 0,
        },
    },

    storyteller: {
        id: "storyteller",
        name: "Storyteller",
        description: "Cozy fireside storytelling experience",
        icon: "flame",
        theme: {
            background: "#1a1410",
            surface: "#2a2018",
            accent: "#d97706",
            text: "#fef3c7",
            textMuted: "#a8a29e",
            borderRadius: "lg",
            shadows: "soft",
            vignette: 0.4,
            grain: 0.15,
            warmth: 0.3,
            saturation: 0.85,
        },
        controls: {
            showProgressBar: true,
            showTimeDisplay: true,
            showPlaybackSpeed: false,
            showVolumeControl: true,
            showFullscreen: true,
            showChapters: true,
            showBookmarks: true,
            navigationStyle: "chapter-based",
            showPageControls: true,
            showPageIndicator: true,
            allowManualPageTurn: true,
            autoHideControls: true,
            autoHideDelay: 5000,
            controlsPosition: "bottom",
            controlsOpacity: 0.9,
            swipeToNavigate: true,
            tapToPlayPause: true,
            doubleTapToSeek: false,
            sleepTimer: true,
            abLoop: false,
            frameStep: false,
            annotations: false,
        },
        effects: {
            defaultFilters: {
                brightness: 0.95,
                contrast: 1.05,
                saturation: 0.9,
                hue: 0,
                blur: 0,
                sepia: 0.15,
                grayscale: 0,
            },
            transitionStyle: "fade",
            transitionDuration: 1500,
            letterbox: false,
            letterboxRatio: 16 / 9,
            kenBurnsEnabled: true,
            kenBurnsIntensity: 0.3,
            parallaxEnabled: false,
        },
        behavior: {
            autoPlay: true,
            loop: false,
            defaultSpeed: 0.95,
            pauseBetweenChapters: true,
            chapterPauseDuration: 2000,
            rememberPosition: true,
            showProgressOnHover: false,
            autoAdvance: true,
            advanceDelay: 1500,
            requireInteraction: false,
            sleepTimerOptions: [15, 30, 45, 60],
            fadeOutOnSleep: true,
            syncTextHighlight: true,
            syncAnimations: true,
        },
        audio: {
            ambientSound: AMBIENT_SOUNDS.find(s => s.id === "fireplace"),
            ambientVolume: 0.25,
            backgroundMusicDuck: true,
            duckAmount: 0.4,
            duckFadeDuration: 800,
            voiceBoost: true,
            voiceBoostAmount: 2,
            spatialAudio: false,
            transitionSound: "chime-soft",
            transitionSoundVolume: 0.3,
        },
    },

    audiobook: {
        id: "audiobook",
        name: "Audiobook",
        description: "Page-based reading experience with manual controls",
        icon: "book-open",
        theme: {
            background: "#faf6f1",
            surface: "#ffffff",
            accent: "#059669",
            text: "#1f2937",
            textMuted: "#6b7280",
            borderRadius: "sm",
            shadows: "soft",
            vignette: 0,
            grain: 0,
            warmth: 0.1,
            saturation: 1,
        },
        controls: {
            showProgressBar: true,
            showTimeDisplay: true,
            showPlaybackSpeed: true,
            showVolumeControl: true,
            showFullscreen: true,
            showChapters: true,
            showBookmarks: true,
            navigationStyle: "page-based",
            showPageControls: true,
            showPageIndicator: true,
            allowManualPageTurn: true,
            autoHideControls: false,
            autoHideDelay: 0,
            controlsPosition: "bottom",
            controlsOpacity: 1,
            swipeToNavigate: true,
            tapToPlayPause: true,
            doubleTapToSeek: false,
            sleepTimer: true,
            abLoop: true,
            frameStep: false,
            annotations: true,
        },
        effects: {
            defaultFilters: {
                brightness: 1,
                contrast: 1,
                saturation: 1,
                hue: 0,
                blur: 0,
                sepia: 0,
                grayscale: 0,
            },
            transitionStyle: "page-turn",
            transitionDuration: 400,
            letterbox: false,
            letterboxRatio: 16 / 9,
            frameOverlay: "book-page",
            kenBurnsEnabled: false,
            kenBurnsIntensity: 0,
            parallaxEnabled: false,
        },
        behavior: {
            autoPlay: false,
            loop: false,
            defaultSpeed: 1,
            pauseBetweenChapters: true,
            chapterPauseDuration: 0,
            rememberPosition: true,
            showProgressOnHover: true,
            autoAdvance: false,
            advanceDelay: 0,
            requireInteraction: true,
            sleepTimerOptions: [15, 30, 45, 60, 90, 120],
            fadeOutOnSleep: true,
            syncTextHighlight: true,
            syncAnimations: false,
        },
        audio: {
            ambientVolume: 0,
            backgroundMusicDuck: true,
            duckAmount: 0.5,
            duckFadeDuration: 300,
            voiceBoost: true,
            voiceBoostAmount: 3,
            spatialAudio: false,
            transitionSound: "page-turn",
            transitionSoundVolume: 0.2,
        },
    },

    cinema: {
        id: "cinema",
        name: "Cinema",
        description: "Immersive movie theater experience",
        icon: "film",
        theme: {
            background: "#000000",
            surface: "#0a0a0a",
            accent: "#ef4444",
            text: "#ffffff",
            textMuted: "#737373",
            borderRadius: "none",
            shadows: "none",
            vignette: 0.2,
            grain: 0.05,
            warmth: 0,
            saturation: 1.05,
        },
        controls: {
            showProgressBar: true,
            showTimeDisplay: true,
            showPlaybackSpeed: false,
            showVolumeControl: true,
            showFullscreen: true,
            showChapters: true,
            showBookmarks: false,
            navigationStyle: "continuous",
            showPageControls: false,
            showPageIndicator: false,
            allowManualPageTurn: false,
            autoHideControls: true,
            autoHideDelay: 2000,
            controlsPosition: "overlay",
            controlsOpacity: 0.8,
            swipeToNavigate: false,
            tapToPlayPause: true,
            doubleTapToSeek: true,
            sleepTimer: false,
            abLoop: false,
            frameStep: false,
            annotations: false,
        },
        effects: {
            defaultFilters: {
                brightness: 1,
                contrast: 1.1,
                saturation: 1.05,
                hue: 0,
                blur: 0,
                sepia: 0,
                grayscale: 0,
            },
            transitionStyle: "fade",
            transitionDuration: 500,
            letterbox: true,
            letterboxRatio: 2.35,
            kenBurnsEnabled: false,
            kenBurnsIntensity: 0,
            parallaxEnabled: false,
        },
        behavior: {
            autoPlay: true,
            loop: false,
            defaultSpeed: 1,
            pauseBetweenChapters: false,
            chapterPauseDuration: 0,
            rememberPosition: true,
            showProgressOnHover: true,
            autoAdvance: true,
            advanceDelay: 0,
            requireInteraction: false,
            sleepTimerOptions: [],
            fadeOutOnSleep: false,
            syncTextHighlight: false,
            syncAnimations: false,
        },
        audio: {
            ambientVolume: 0,
            backgroundMusicDuck: false,
            duckAmount: 0,
            duckFadeDuration: 0,
            voiceBoost: false,
            voiceBoostAmount: 0,
            spatialAudio: true,
            transitionSoundVolume: 0,
        },
    },

    presentation: {
        id: "presentation",
        name: "Presentation",
        description: "Slide-based presentation mode",
        icon: "presentation",
        theme: {
            background: "#1e293b",
            surface: "#334155",
            accent: "#3b82f6",
            text: "#f1f5f9",
            textMuted: "#94a3b8",
            borderRadius: "md",
            shadows: "medium",
            vignette: 0,
            grain: 0,
            warmth: 0,
            saturation: 1,
        },
        controls: {
            showProgressBar: true,
            showTimeDisplay: true,
            showPlaybackSpeed: false,
            showVolumeControl: true,
            showFullscreen: true,
            showChapters: true,
            showBookmarks: false,
            navigationStyle: "page-based",
            showPageControls: true,
            showPageIndicator: true,
            allowManualPageTurn: true,
            autoHideControls: false,
            autoHideDelay: 0,
            controlsPosition: "side",
            controlsOpacity: 1,
            swipeToNavigate: true,
            tapToPlayPause: false,
            doubleTapToSeek: false,
            sleepTimer: false,
            abLoop: false,
            frameStep: false,
            annotations: true,
        },
        effects: {
            defaultFilters: {
                brightness: 1,
                contrast: 1,
                saturation: 1,
                hue: 0,
                blur: 0,
                sepia: 0,
                grayscale: 0,
            },
            transitionStyle: "slide",
            transitionDuration: 300,
            letterbox: false,
            letterboxRatio: 16 / 9,
            kenBurnsEnabled: false,
            kenBurnsIntensity: 0,
            parallaxEnabled: false,
        },
        behavior: {
            autoPlay: false,
            loop: false,
            defaultSpeed: 1,
            pauseBetweenChapters: true,
            chapterPauseDuration: 0,
            rememberPosition: false,
            showProgressOnHover: true,
            autoAdvance: false,
            advanceDelay: 0,
            requireInteraction: true,
            sleepTimerOptions: [],
            fadeOutOnSleep: false,
            syncTextHighlight: false,
            syncAnimations: true,
        },
        audio: {
            ambientVolume: 0,
            backgroundMusicDuck: false,
            duckAmount: 0,
            duckFadeDuration: 0,
            voiceBoost: false,
            voiceBoostAmount: 0,
            spatialAudio: false,
            transitionSoundVolume: 0,
        },
    },

    learning: {
        id: "learning",
        name: "Learning",
        description: "Educational mode with practice tools",
        icon: "graduation-cap",
        theme: {
            background: "#0f172a",
            surface: "#1e293b",
            accent: "#8b5cf6",
            text: "#e2e8f0",
            textMuted: "#94a3b8",
            borderRadius: "md",
            shadows: "medium",
            vignette: 0,
            grain: 0,
            warmth: 0,
            saturation: 1,
        },
        controls: {
            showProgressBar: true,
            showTimeDisplay: true,
            showPlaybackSpeed: true,
            showVolumeControl: true,
            showFullscreen: true,
            showChapters: true,
            showBookmarks: true,
            navigationStyle: "continuous",
            showPageControls: false,
            showPageIndicator: false,
            allowManualPageTurn: false,
            autoHideControls: false,
            autoHideDelay: 0,
            controlsPosition: "bottom",
            controlsOpacity: 1,
            swipeToNavigate: false,
            tapToPlayPause: true,
            doubleTapToSeek: true,
            sleepTimer: false,
            abLoop: true,
            frameStep: true,
            annotations: true,
        },
        effects: {
            defaultFilters: {
                brightness: 1,
                contrast: 1,
                saturation: 1,
                hue: 0,
                blur: 0,
                sepia: 0,
                grayscale: 0,
            },
            transitionStyle: "cut",
            transitionDuration: 0,
            letterbox: false,
            letterboxRatio: 16 / 9,
            kenBurnsEnabled: false,
            kenBurnsIntensity: 0,
            parallaxEnabled: false,
        },
        behavior: {
            autoPlay: false,
            loop: false,
            defaultSpeed: 1,
            pauseBetweenChapters: true,
            chapterPauseDuration: 1000,
            rememberPosition: true,
            showProgressOnHover: true,
            autoAdvance: false,
            advanceDelay: 0,
            requireInteraction: false,
            sleepTimerOptions: [30, 60, 90],
            fadeOutOnSleep: true,
            syncTextHighlight: true,
            syncAnimations: true,
        },
        audio: {
            ambientVolume: 0,
            backgroundMusicDuck: true,
            duckAmount: 0.5,
            duckFadeDuration: 300,
            voiceBoost: true,
            voiceBoostAmount: 2,
            spatialAudio: false,
            transitionSoundVolume: 0,
        },
    },

    journey: {
        ...moodBase,
        id: "journey",
        name: "Journey",
        icon: "orbit",
        description: "All characters together — 4-quadrant radial spectrum",
        theme: {
            background: "#0e0806",
            surface: "#1a1008",
            accent: "#C8941A",
            text: "#fef3c7",
            textMuted: "#a8996e",
            borderRadius: "lg",
            shadows: "dramatic",
            vignette: 0.3,
            grain: 0.1,
            warmth: 0.2,
            saturation: 1,
        },
    },
    dock: {
        ...moodBase,
        id: "dock",
        name: "Dock",
        icon: "disc-3",
        description: "Spinning vinyl under a warm harbour light",
        theme: {
            background: "#0b0905",
            surface: "#1a1408",
            accent: "#D4A04A",
            text: "#fef3c7",
            textMuted: "#a8906a",
            borderRadius: "lg",
            shadows: "soft",
            vignette: 0.25,
            grain: 0.12,
            warmth: 0.3,
            saturation: 0.9,
        },
    },
    storm: {
        ...moodBase,
        id: "storm",
        name: "Storm",
        icon: "zap",
        description: "Lightning frequency bars in the electric dark",
        theme: {
            background: "#050912",
            surface: "#0d1424",
            accent: "#1ABCD4",
            text: "#e0f2ff",
            textMuted: "#6aadcc",
            borderRadius: "none",
            shadows: "dramatic",
            vignette: 0.15,
            grain: 0.05,
            warmth: -0.2,
            saturation: 1.1,
        },
    },
    fest: {
        ...moodBase,
        id: "fest",
        name: "Fest",
        icon: "sparkles",
        description: "Concert stage — spotlights, crowd, circular spectrum",
        theme: {
            background: "#08040f",
            surface: "#180a2a",
            accent: "#A060D8",
            text: "#f0e8ff",
            textMuted: "#9070b8",
            borderRadius: "md",
            shadows: "dramatic",
            vignette: 0.2,
            grain: 0.08,
            warmth: 0,
            saturation: 1.05,
        },
    },
    rock: {
        ...moodBase,
        id: "rock",
        name: "Rock",
        icon: "guitar",
        description: "Distorted bars, rising embers, raw electric energy",
        theme: {
            background: "#0f0203",
            surface: "#1f0505",
            accent: "#E83A14",
            text: "#fff0ec",
            textMuted: "#c07060",
            borderRadius: "none",
            shadows: "dramatic",
            vignette: 0.2,
            grain: 0.12,
            warmth: 0.1,
            saturation: 1.1,
        },
    },
    pop: {
        ...moodBase,
        id: "pop",
        name: "Pop",
        icon: "mic-2",
        description: "Neon bubbles, rainbow bars, sparkles",
        theme: {
            background: "#080115",
            surface: "#18053a",
            accent: "#F72585",
            text: "#ffe4f7",
            textMuted: "#c060a0",
            borderRadius: "lg",
            shadows: "dramatic",
            vignette: 0.15,
            grain: 0.04,
            warmth: -0.05,
            saturation: 1.15,
        },
    },
    disco: {
        ...moodBase,
        id: "disco",
        name: "Disco",
        icon: "disc-2",
        description: "Spinning disco ball, mirrored bars, light projections",
        theme: {
            background: "#02020f",
            surface: "#0b0820",
            accent: "#FFD700",
            text: "#fff8e0",
            textMuted: "#c8a830",
            borderRadius: "md",
            shadows: "dramatic",
            vignette: 0.18,
            grain: 0.06,
            warmth: 0.15,
            saturation: 1.05,
        },
    },
    mixer: {
        id: "mixer",
        name: "Mixer",
        description: "Two-deck DJ mixer with crossfader and per-deck waveform",
        icon: "sliders-horizontal",
        theme: {
            background: "#030712",
            surface: "#111827",
            accent: "#06b6d4",
            text: "#e5e7eb",
            textMuted: "#6b7280",
            borderRadius: "md",
            shadows: "dramatic",
            vignette: 0,
            grain: 0,
            warmth: -0.1,
            saturation: 1,
        },
        controls: {
            showProgressBar: false,
            showTimeDisplay: false,
            showPlaybackSpeed: false,
            showVolumeControl: false,
            showFullscreen: false,
            showChapters: false,
            showBookmarks: false,
            navigationStyle: "continuous",
            showPageControls: false,
            showPageIndicator: false,
            allowManualPageTurn: false,
            autoHideControls: false,
            autoHideDelay: 0,
            controlsPosition: "bottom",
            controlsOpacity: 1,
            swipeToNavigate: false,
            tapToPlayPause: false,
            doubleTapToSeek: false,
            sleepTimer: false,
            abLoop: false,
            frameStep: false,
            annotations: false,
        },
        effects: {
            defaultFilters: {
                brightness: 1,
                contrast: 1,
                saturation: 1,
                hue: 0,
                blur: 0,
                sepia: 0,
                grayscale: 0,
            },
            transitionStyle: "cut",
            transitionDuration: 0,
            letterbox: false,
            letterboxRatio: 16 / 9,
            kenBurnsEnabled: false,
            kenBurnsIntensity: 0,
            parallaxEnabled: false,
        },
        behavior: {
            autoPlay: false,
            loop: false,
            defaultSpeed: 1,
            pauseBetweenChapters: false,
            chapterPauseDuration: 0,
            rememberPosition: false,
            showProgressOnHover: false,
            autoAdvance: false,
            advanceDelay: 0,
            requireInteraction: false,
            sleepTimerOptions: [],
            fadeOutOnSleep: false,
            syncTextHighlight: false,
            syncAnimations: false,
        },
        audio: {
            ambientVolume: 0,
            backgroundMusicDuck: false,
            duckAmount: 0,
            duckFadeDuration: 0,
            voiceBoost: false,
            voiceBoostAmount: 0,
            spatialAudio: false,
            transitionSoundVolume: 0,
        },
    },
};
